### ISSUE TITLE
Test failing

### ISSUE THREAD

**Issue by Fale** [DiffSK/configobj#100]
As title:

    py.test-3.4 tests
    ============================= test session starts ==============================
    platform linux -- Python 3.4.3 -- py-1.4.30 -- pytest-2.7.3
    rootdir: /builddir/build/BUILD/configobj-5.0.6, inifile: 
    collected 71 items
    
    tests/test_configobj.py .F............................................................
    tests/test_validate.py ...
    tests/test_validate_errors.py ......
    
    =================================== FAILURES ===================================
    ___________________________ test_options_deprecation ___________________________
    
        def test_options_deprecation():
            with catch_warnings(record=True) as log:
                ConfigObj(options={})
        
            # unpack the only member of log
            try:
                warning, = log
            except ValueError:
    >           assert len(log) == 1
    E           assert 0 == 1
    E            +  where 0 = len([])
    
    tests/test_configobj.py:117: AssertionError
    ===================== 1 failed, 70 passed in 0.33 seconds ======================

**Comment by Fale** [comment]
It seems like 

    export PYTHONWARNINGS=always

fixes it ;/

**Comment by jhermann** [comment]
fixed in 7431553d
