### ISSUE TITLE
Not possible to open 2+ config files into same configobj instance?

### ISSUE THREAD

**Issue by Teslafly** [DiffSK/configobj#103]
It does not seem possible to load 2 or more files into the same configobj instance. 

In configparser, You could load multiple files into the same dictionary because it had a separate file load function, like so:

sysconf = configparser.SafeConfigParser()
sysconf.read(file1)
sysconf.read(file2)

Because configobj loads the file in it's class init, this does not seem possible for configobj in it's current state

loading multiple files is useful for when you have a large set of configuration options that have to be human readable and may need to be partially duplicated with slightly different settings for some sections 

The human readable part is why I don't move to xml, and why the nesting limitation in configparser gives me a headache.

(Granted, I just found cofigobj when searching for a solution to human readable arbitrary nesting alternatives for configparser and only skimmed the documentation, so I may have missed something that wasn't obvious.)

**Comment by EliAndrewC** [comment]
The function you want is ``ConfigObj.merge``.  For example, suppose we have ``config1.ini`` with the following contents:

```
foo = "Hello World"
bar = "Yello World"
```

and ``config2.ini`` with the following contents:

```
foo = "Hello Kitty"
baz = "Goodbye World"
```

We can do the following:

```python
>>> from configobj import ConfigObj
>>> conf = ConfigObj('config1.ini')
>>> conf.merge(ConfigObj('config2.ini'))
>>> conf
ConfigObj({'foo': 'Hello Kitty', 'bar': 'Yello World', 'baz': 'Goodbye World'})
```

As you can see, this had the following semantics:
- ``foo`` appeared in both ``config1.ini`` and ``config2.ini`` which means that the one loaded second "won" and its value was the final result
- ``bar`` and ``baz`` each appeared in a single file, so they were just both added to the config object with no values being overwritten

Let me know if you believe this meets your use case.

**Comment by Teslafly** [comment]
Thanks. That was exactly what I was looking for.

It may be pertinent to add a note about the merge() near 'reading a config file' in documentation as they are heavily related.

For loading a list of config files, something like this should work out, correct?
```
>>> from configobj import ConfigObj
>>> conf = ConfigObj() 

>>> for file in files:
>>>     conf.merge(ConfigObj(file))
```

**Comment by EliAndrewC** [comment]
What you posted should indeed work.

Your point is taken with updating the docs; we'll keep that in mind next time we're doing doc updates.  I was surprised to learn that there's not even an easy way to link to the ``merge`` function in the docs!

**Comment by Teslafly** [comment]
hmm. experimenting a bit, your library is sound (thanks!), but while merge() is quite useful in it's own way, a utility function mimicking read() from configparser may be a useful addition.

this is beacuse by creating a new instance of the class and merging it, you do not preserve the original configuration of the parser. 

example:
from configobj import ConfigObj  #alternative configparser that allows nesting
sysconf = ConfigObj(interpolation = 'ConfigParser')

**Comment by jhermann** [comment]
@EliAndrewC Depending on your definition of easy, 

    py:func:`qualified.name` 

is hard?

**Comment by EliAndrewC** [comment]
> Depending on your definition of easy

Fair point; what I meant by "no easy way" was that I expected the table of contents at the top to have a link to the "merge" function which I could copy.  I might just be biased towards my own personal use cases, but I consider ``merge`` to be a huge part of the value of ConfigObj since I use it pretty much everywhere, so I was surprised that "Merging multiple config files" wasn't a whole section of the docs.

> should this be put in a new issue? (probably)

I think so, compatibility with ConfigParser has never been a strict requirement for ConfigObj, but I think supporting their API as closely as is reasonable is a good design goal.
