### ISSUE TITLE
Documentation of mixed_list

### ISSUE THREAD

**Issue by Koris** [DiffSK/configobj#110]
There is a discrepancy in the documentation of mixed_list. In the html, it is said to work as mixed_list(str, int), while actually it is mixed_list('string', 'integer').

See https://github.com/DiffSK/configobj/search?utf8=%E2%9C%93&q=mixed_list
and you will see what I mean

**Comment by EliAndrewC** [comment]
Whoops, at a glance, it looks like you're right.  I've never actually used ``mixed_list`` before, so I never noticed!

**Comment by jhermann** [comment]
I adapted the code to the docs instead of the other way 'round, to also handle inconsistencies like ``integer`` vs. ``int_list`` (not ``integer_list``) vs. built-in type ``int`` – for built-in types, you can now use all 3 forms (non-quoted type name, short name, long name).
