### ISSUE TITLE
Copying configobj

### ISSUE THREAD

**Issue by FlavioAlexander** [DiffSK/configobj#115]
Hello,

Is there a way to copy the configobj instance? I know there there is a copy method, but it returns a `type dict`.  I want to be able to modify the copy and return its result without affecting the original object. 

Best,

Flavio

**Comment by jhermann** [comment]
Use ``merge`` to copy the values into a new, empty ConfigObj.

**Comment by FlavioAlexander** [comment]
@jhermann Thanks for your response. I have tried merge. However, if I modify the new copy,  e.g. delete a section, the original 'configobj object' gets modified as well.

**Comment by jhermann** [comment]
Looking at the code, mutable objects (sections) are copied as-is; means you need to apply deepcopy to untangle the two objects fully.

**Comment by FlavioAlexander** [comment]
I ended up `deepcopying` section by section and it worked, thanks for your help.

**Comment by jhermann** [comment]
Keeping this open to either document it, or add it to the code (possibly as a keyword param of `merge()`).
