### ISSUE TITLE
DeprecationWarning: BaseException.message has been deprecated as of Python 2.6

### ISSUE THREAD

**Issue by kierun** [DiffSK/configobj#119]
Using `configobj (5.0.6)`, I tried the following and got a `DeprecationWarning`:

```
Python 2.7.5 (default, Aug 18 2016, 15:58:25)
Type "copyright", "credits" or "license" for more information.

IPython 5.0.0 -- An enhanced Interactive Python.
?         -> Introduction and overview of IPython's features.
%quickref -> Quick reference.
help      -> Python's own help system.
object?   -> Details about 'object', use 'object??' for extra details.

In [1]: from configobj import ConfigObj
   ...: from configobj import ConfigObjError
   ...:
   ...:     cfg = [str('thing  {"a": 1}')]
   ...:     c = ConfigObj(cfg)
   ...: except ConfigObjError as ex:
   ...:     print(ex.errors)
   ...:     for error in ex.errors:
   ...:         print(error.message)
   ...:
[ParseError('Invalid line (\'thing  {"a": 1}\') (matched as neither section nor keyword) at line 1.',)]
/home/yann/.virtualenvs/rprs_bootstrap/bin/ipython:7: DeprecationWarning: BaseException.message has been deprecated as of Python 2.6
  from IPython import start_ipython
Invalid line ('thing  {"a": 1}') (matched as neither section nor keyword) at line 1.
```

Same with plain Python:

```
Python 2.7.5 (default, Aug 18 2016, 15:58:25)
[GCC 4.8.5 20150623 (Red Hat 4.8.5-4)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from configobj import ConfigObj
>>> from configobj import ConfigObjError
>>>
>>> try:
...     cfg = [str('thing  {"a": 1}')]
...     c = ConfigObj(cfg)
... except ConfigObjError as ex:
...     print(ex.errors)
...     for error in ex.errors:
...         print(error.message)
...
[ParseError('Invalid line (\'thing  {"a": 1}\') (matched as neither section nor
keyword) at line 1.',)]
Invalid line ('thing  {"a": 1}') (matched as neither section nor keyword) at line 1.
```

Am I doing the catching wrong somehow?

**Comment by jhermann** [comment]
Prefer str(ex), or even better, use it in a format (then the str is implicit). Basically you are duplicating the code in the ``__str__`` of the exception.

**Comment by kierun** [comment]
That works even better for me!

Should the [documentation on exceptions](http://configobj.readthedocs.io/en/latest/configobj.html#exceptions) be updated to reflect that or is it just me being dense?

**Comment by jhermann** [comment]
Docs can certainly be improved, PRs would help to that.

Also consider testing your code with git head, parsing errors were improved (#73).

**Comment by kierun** [comment]
Not sure if this merits a PR for a few lines of text but as soon as my other one is either trashed or modified, I can submit a new one.  To be fair, I was a little dense: `__str__` is kinda the Pythonic way to print exceptions. ^_~

**Comment by jhermann** [comment]
> Not sure if this merits a PR for a few lines of text…

Use the embedded editor of GitHub for that and it becomes a breeze (GH basically does everything for you, including the initial fork). Try it, you'll like it.

**Comment by kierun** [comment]
\grins I'll give that a go tomorrow…

**Comment by kierun** [comment]
Done a [PR](https://github.com/DiffSK/configobj/compare/master...kierun:patch-1). You were right, the editor is good.

**Comment by hugovk** [comment]
Can this be closed now https://github.com/DiffSK/configobj/pull/120 is merged?

**Comment by kierun** [comment]
I guess it can…
