### ISSUE TITLE
List parsing in config.ini

### ISSUE THREAD

**Issue by nitin-tm** [DiffSK/configobj#121]
Hi ,

I am currently using the configobj version 5.0.6 .I am trying to parse list with multiple items as a value , parsing this getting me error.

eg from datamass.ini

172: files = ["stdout", "/tmp/metrics.out"]

**"""**
**ConfigObj('datamass.ini')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/configobj.py", line 1229, in **init**
    self._load(infile, configspec)
  File "/usr/local/lib/python2.7/dist-packages/configobj.py", line 1318, in _load
    error.config = self
configobj.ConfigObjError: Parsing failed with several errors.
First error at line 172.**
"""
Could please check whether it is supported or not ?

**Comment by jhermann** [comment]
Please consult the manual for the correct syntax (which is not Python's, just similar at places): http://configobj.readthedocs.io/en/stable/configobj.html#the-config-file-format
