### ISSUE TITLE
No wheel for latest version 5.0.6

### ISSUE THREAD

**Issue by adamchainz** [DiffSK/configobj#123]
This project has `bdist_wheel` configuration in its `setup.cfg` but no wheel has been published. This implies that the `bdist_wheel` step was missed in release. A full sdist + bdist_wheel release can be done with `python setup.py clean sdist bdist_wheel upload`. You can also upload the wheel for 5.0.6 now by checking out the source code at that point and running `python setup.py clean bdist_wheel upload`. This will speed up everyone's installs 🐇 😄

**Comment by robdennis** [comment]
5.0.7 does have a wheel, please re-open / make a new ticket if this doesn't address your needs.

**Comment by adamchainz** [comment]
Thank you.
