### ISSUE TITLE
Inconsistent license

### ISSUE THREAD

**Issue by richardwhiuk** [DiffSK/configobj#143]
The license information provided in this project is inconsistent:

https://github.com/DiffSK/configobj/blob/master/docs/configobj.rst#license - refers to 2005-2014.

https://github.com/DiffSK/configobj/blob/master/LICENSE - refers to 2003-2014, but doesn't include Nicola Larosa

https://github.com/DiffSK/configobj/blob/master/docs/configobj.html#L2114-L2155 refers to 2004-2010 and only includes Michael Foord and Nicola Larosa.

None of these are up to date (i.e. with anything done in the last 3 years).

**Comment by robdennis** [comment]
there's some sort of alignment that needs to happen with all this

**Comment by robdennis** [comment]
> https://github.com/DiffSK/configobj/blob/master/docs/configobj.html#L2114-L2155 refers to 2004-2010 and only includes Michael Foord and Nicola Larosa.

This is a _compiled_ version of the .rst files, and I believe the action is to remove all the compiled files (this should have always been the case)
