### ISSUE TITLE
Getting "None" on empty fields

### ISSUE THREAD

**Issue by pouldenton** [DiffSK/configobj#150]
Hello!

I'm writing config file from Django DB like this:

```
from .models import Model
model_instance = Model.objects.get(id=4)
conf = ConfigObj()
conf.filename = '/test.cfg'
for field in model_instance._meta.fields:
    conf[field.name] = getattr(model, field.name)
conf.write()
```

There are some integer fields, like "port" that can be empty in DB.

```
>>>conf
ConfigObj({'port': None})
```
`conf.get("port")` return nothing, as expected:

```
>>>conf.get("port")

```

Inside file "/test.cfg" it looks like this:

> port = None

But when we try to read this value from file:

```
a=ConfigObj('/test.cfg')
a.get("port")

```
It return string:

>  'None' 

This happens with ConfigObj 5.0.6 and python 3.5.2

**Comment by robdennis** [comment]
this reads to me as "The default type for config value is string" with a dash of "there are some expectations around NoneType that aren't matching what happens"

and I don't think I'm able to do anything about either of these in 5.1.0. I think there's probably some sort of feature request around NoneType that I could see, but I'm going to close this to stay focused on 5.1.0
