### ISSUE TITLE
New release to pypi server

### ISSUE THREAD

**Issue by slitayem** [DiffSK/configobj#160]
Can you please release a new version from master branch. The last release `5.0.6` is from 2014.

Thanks.

**Comment by slitayem** [comment]
@jhermann Can you please do that ?

**Comment by kiddick** [comment]
bump

**Comment by bsipocz** [comment]
Hi,
Is there a ETA for the next release please?

**Comment by fmaussion** [comment]
I came into [this issue](https://github.com/DiffSK/configobj/issues/91) today: for some inexplicable reason, the configobj package on pypi is named `5.0.6` but is dated from Aug 26, 2014. The file shipped with pypi contains this error: you can check it by yourself by downloading the package on pypi (https://pypi.org/project/configobj/#files) and open `configobj.py`

The header reads:

```python
...
from _version import __version__
```

Where it should import from ``._version`` instead. No idea how this old file made it to pypi but this should be corrected. Is anybody on this thread now using an alternative lib, or do you install from github instead?

**Comment by hoechenberger** [comment]
> or do you install from github instead?

This. Unfortunately.

**Comment by fmaussion** [comment]
@jhermann any news on a PyPi release?

**Comment by vazhnov** [comment]
Last commit to master branch = 3 month ago.
Last release = 5 years ago.
Is this right time to release new version?

**Comment by Sinan81** [comment]
wasted several hours on this. The version on PyPi even doesn't compile. Waiting for the above mentioned milestones to be completed, which seems to be overdue.

**Comment by hoechenberger** [comment]
I've created a "packaging fork" of `configobj`, meaning I simply copied `configobj:master` and released it to PyPI and `conda-forge` as `configobj-dev`. As the name of the installed package remains unchanged, can be used as a drop-in replacement for `configobj`. See https://github.com/hoechenberger/configobj-dev/#configobj-dev

Hope this makes life for some of you a little easier!

**Comment by ericfrederich** [comment]
Someone should make a new release of this.  I cannot use [click-config-file](https://github.com/phha/click_config_file) in conjunction with [versioneer](https://github.com/warner/python-versioneer) because of #91.

**Comment by robdennis** [comment]
I think this is related to #213  / #204 so I'm going to track it there
