### ISSUE TITLE
Case insensitive dictionary keys

### ISSUE THREAD

**Issue by onvav** [DiffSK/configobj#161]
Hello,
as I understand the configObj dictionary should be case insensitive so both statements should work:
config['section1']
config['SECTION1']

But it doesn't work. Is it bug or I missed something?

**Comment by jhermann** [comment]
Without having checked the code, your assumption possibly only holds true for value keys, not section names.

**Comment by robdennis** [comment]
I'm inclined to close this but people want this in 5.1.0 please comment
