### ISSUE TITLE
Question: How to set parser to ignore errors?

### ISSUE THREAD

**Issue by anoopjb** [DiffSK/configobj#164]
I am trying to edit snmptt.ini configuration file. This configuration file seems to be generated from a perl script. It also has lots of useful comments in the configuration file.

The built-in configparser works with strict option set to false.
```
import configparser
config = configparser.ConfigParser(allow_no_value=True, strict=False, interpolation=None)
config.read('/etc/snmp/snmptt.ini')
```

Is there any option in configobj to ignore errors in config file?
I am using configobj (5.0.6) on Python 3.5.2 
[snmptt.txt](https://github.com/DiffSK/configobj/files/1650549/snmptt.txt)

**Comment by jhermann** [comment]
See #135

**Comment by anoopjb** [comment]
Please update the documentation.

> https://configobj.readthedocs.io/en/latest/configobj.html

Thanks.
