### ISSUE TITLE
unable to install validation under python 3.6

### ISSUE THREAD

**Issue by millerthegorilla** [DiffSK/configobj#178]
python 3.6 complains about a syntax error:
`except` Exception, e:
when installing using pycharm
full error:
Collecting validate
  Downloading https://files.pythonhosted.org/packages/02/f8/97105237d0ba693b6f0bdcd94da0504e9a4433988c4393d8d3049094be7a/validate-1.0.1.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pycharm-packaging/validate/setup.py", line 13, in <module>
        from configobj import __version__ as VERSION
      File "/tmp/pycharm-packaging/validate/configobj.py", line 1632
        except Exception, e:
                        ^
    SyntaxError: invalid syntax

**Comment by jhermann** [comment]
Use a recent release, validation is now integrated (see changelog).

**Comment by tsroten** [comment]
Hello @jhermann! It looks like the latest release still has the validate.py module outside of a configobj package. The changelog references a version 5.1.0, but I don't see that release on [GitHub](https://github.com/DiffSK/configobj/releases) or [PyPI](https://pypi.org/project/configobj/). There also doesn't seem to be a [version tag](https://github.com/DiffSK/configobj/tags) for it either.

Is there another way we should be looking at upgrading to a release newer than 5.0.6?

**Comment by jhermann** [comment]
Sorry, I was sure I pushed out all those changes, but I didn't. Guess it is high time to push out what's there.

For the time being, use this requirement:

    https://github.com/DiffSK/configobj/archive/master.zip#egg=configobj
