### ISSUE TITLE
Multiple sets of quotes not parsed correctly

### ISSUE THREAD

**Issue by frakman1** [DiffSK/configobj#179]
I  have a config file with the section `[Scripts]` designed to allow someone to enter script shortcuts. 
They would enter a string exactly as it would appear on the Windows command line.

Example:

```
[Scripts]
ssh myserver = "C:\Program Files (x86)\Mobatek\MobaXterm\MobaXterm.exe" -bookmark "my.url.com (username)"
```
My code that parses it, looks like this:

```python
config = ConfigObj(config_path)
for key, value in config['Scripts'].items():
    print ("key:{} value:{}".format(key, value))
    # <etc> ...
```
Unfortunately, the `value` component is missing the first and last `"` 
Output:
```
key:ssh myserver value:C:\Program Files (x86)\Mobatek\MobaXterm\MobaXterm.exe" -bookmark "my.url.com (username)
```

**Comment by frakman1** [comment]
I have since learned that there is a configObj option called `unrepr` that should be used. It has the unfortunate side-effect of requiring ALL values in the config file to be quoted (not just the [Scripts] section) otherwise, it will throw a parsing error.

I had to use this form:
```python
ConfigObj(config_path, raise_errors = True, unrepr=True)
```
as well as put single quotes around the whole script like this before it worked:

```
[Scripts]
ssh myserver = '"C:\Program Files (x86)\Mobatek\MobaXterm\MobaXterm.exe" -bookmark "my.url.com (username)"'
```

**Comment by robdennis** [comment]
thanks for leaving this; I'm closing this but hope it acts as documentation
