### ISSUE TITLE
Getting "None" on some fields on some computers. What could cause this?

### ISSUE THREAD

**Issue by komodovaran** [DiffSK/configobj#190]
I have a GUI that adjusts according to a set of values on startup.

On my computer it reads all values fine. On somebody else's computer, it reads almost all values, _but returns `None` instead of a float for a specific line_.

E.g. in the config.ini I would read the following keys:
```
val1 = 0 # returns 0
val2 = 0 # returns 0
val3 = 0 # returns None??
```

What could cause this? All the other values are seemingly read without problems. Both computers are using configobj 5.0.6.

**Comment by robdennis** [comment]
I don't think I have enough information to just know, but as a complete guess (and assuming it's the last line in the file), maybe there's something with different OS line endings

I think I'm declaring bankruptcy on this, just for the limited scope I'm _actually_ able to do on a 5.10.0
