### ISSUE TITLE
Write quoted strings without having them wrapped in an additional layer of quotes

### ISSUE THREAD

**Issue by joeydumont** [DiffSK/configobj#198]
I have an app that expects a value to be in the format: 

```ini
pre_install_args = "each word is an argument"
```

I tried writing

```python
config['pre_install_args'] = "\"each word is an argument\""
```

but this results in 

```ini
pre_install_args = '"each word is an argument"'
```

after calling `ConfigObj.write()`. 

To fix the issue, I've modified `ConfigObj._get_single_quote(self, value)` to 

```python
    def _get_single_quote(self, value):
        if ("'" in value) and ('"' in value):
            raise ConfigObjError('Value "%s" cannot be safely quoted.' % value)
        elif re.match('".*"', value) is not None:
            quot = noquot
        elif re.match("'.*'", value) is not None:
            quot = noquot
        elif '"' in value:
            quot = squot
        else:
            quot = dquot
        return quot
```

Note the two new `re.match` branches in the conditional. Works for my needs, but does that make sense in general?

**Comment by raratiru** [comment]
Could this possibly be fixing #202 ?

**Comment by joeydumont** [comment]
I'm not sure how to replicate this. Could you provide the input, the script to create the output, and the expected output? I tried, but I wasn't sure how you got from your JSON root logger to your ini config file, and what you wanted ConfigObj to do.

**Comment by robdennis** [comment]
I appreciate there was a MR for this, and apologies for asking a question about this after 2.5 years, but I want to understand your expected values.

I'm tracking this as "I want a specific string value for ``pre_install_args`` and it shouldn't have any quotes in the final value"

I'd have expected that to be accomplished by:
```
config['pre_install_args'] = "each word is an argument"
```
(note only one set of quotes)

Am I misunderstanding the use case?

**Comment by joeydumont** [comment]
Re-reading this 2.5 years, I realize that my explanation wasn't that great. In any case, I've sinced refactored that code away from my application. Given your concerns, I think it's best to close both this issue and the associated pull request.
