### ISSUE TITLE
Generic _version file toplevel install

### ISSUE THREAD

**Issue by derSeddy** [DiffSK/configobj#203]
When using `pip3` on debian 9 for installing this library, the file `_version.py` is installed to `.local/lib/python3.5/site-packages/_version.py`.
This is a very generic name and causes problems in a completely unrelated project of my company which has a `_version.py` file in it's own subfolder. `import _version` will import the wrong file for the project of my company.

We can probably fix the issue on our side, but is it intended to place a file with such a generic name in this prominent location? Would it be possible to install the library into a sub folder or change the name of the version file to be less generic?

**Comment by jhermann** [comment]
This is solved in git head, while unreleased this requirement helps:

    https://github.com/DiffSK/configobj/archive/master.zip#egg=configobj

**Comment by robdennis** [comment]
this was done in 5.0.7 be executing the change @jhermann mentioned (it should be something we can merge back into master when/if someone wants to take over day-to-day ownership)
