### ISSUE TITLE
Version 5.0.7 has disruptive changes

### ISSUE THREAD

**Issue by romeroyonatan** [DiffSK/configobj#230]
Hi mainteiners,
first of all thanks for maintaining this library. Thanks for your time :)

I just realize that the last version changes the import of validate

Old
```python
import validate
```

New
```python
import configobj.validate
```
I updated my code but I think could be useful to note it in the changelog and, if it is not too much trouble, revert the change in a version 5.0.8 and re apply them in version 6.0.0 to maintain the semantic versioning

Thank you very much again

Have a nice day

**Comment by triplethreatsolutions** [comment]
Discovered the same issue this morning as well.

**Comment by robdennis** [comment]
Thanks everyone, this is in a new milestone for 5.0.8 and will be addressed ASAP

**Comment by icct-galvarez** [comment]
Thanks so much for the support! Since I already modified our codebase to use the new `import configobj.validate` syntax, would it be possible to support both the old and new versions of the import statement in 5.0.8 and beyond so we don't have to go and revert those changes all over again?

**Comment by robdennis** [comment]
Certainly. There are new unit tests that assert each of the following forms work:

```
import validate
```

```
import configobj.validate
```

```
from configobj import validate
```

**Comment by robdennis** [comment]
> I updated my code but I think could be useful to note it in the changelog and, if it is not too much trouble, revert the change in a version 5.0.8 and re apply them in version 6.0.0 to maintain the semantic versioning

Because, as you note, this change would violate semantic versioning, I've:
- yanked it from pypi (with a note why)
- prepping to release 5.0.8 with a changelog that notes this was shipped

**Comment by robdennis** [comment]
https://pypi.org/project/configobj/5.0.8/

**Comment by robdennis** [comment]
if there are new regressions, please open a new issue and I'll close ASAP

**Comment by romeroyonatan** [comment]
Thank you :)
