### ISSUE TITLE
Vulnerable regex detected by Snyk. Please fix or avoid regex

### ISSUE THREAD

**Issue by wannfq** [DiffSK/configobj#240]
https://github.com/DiffSK/configobj/blob/e2ba4457c4651fa54f8d59d8dcdd3da950e956b8/src/configobj/validate.py#L534

**Comment by wannfq** [comment]
Ref: https://learn.snyk.io/lesson/redos/?_gl=1*1w34pg6*_ga*NzgwNjYzODE3LjE2OTE2NDQ3MDc.*_ga_X9SH3KP7B4*MTY5MjE4NTc5OS4yMS4xLjE2OTIxODU4NjEuMC4wLjA.

**Comment by IloBe** [comment]
Additional info:
- https://quay.io/repository/eclipse/che-sidecar-go/manifest/sha256:2243f389534abc38938f454e01b6653b88ff19048ec4c3ecc0a66e652cb017d0?tab=vulnerabilities
- with pip-audit lib:
configobj 5.0.8   GHSA-c33w-24p9-8m24              Failed to fix configobj (5.0.8): failed to fix dependency configobj (5.0.8), unable to find fix version for vulnerability GHSA-c33w-24p9-8m24

**Comment by thebaptiste** [comment]
Maintainers seem to be in long holidays, retired or dead...
See PR #236 opened by @cdcadman since May 17 on this subject.

**Comment by jelmer** [comment]
#236 is now merged, closing this.

**Comment by jelmer** [comment]
@aarondawg14 no, see the discussion on #237
