### ISSUE TITLE
Calling Builder.build raises a NameError

### ISSUE THREAD

**Issue by pmav99** [DiffSK/configobj#61]
Just run some static checkers on `configobj.py` and this issue came up. Calling `Builder.build` raises a `NameError`.

``` python
class Builder
    def build(self, o):
        if m is None:
            raise UnknownType(o.__class__.__name__)
        return m(o)

    # [omitted ]

    def build_Getattr(self, o):
        parent = self.build(o.expr)
        return getattr(parent, o.attrname)
```

This regression, if that is what it is, seems to have been introduced in (f461e506d74bddb48af27923fe3cf6ae40544a64) (Line 146).

Adding back this line should fix it:
``` python
        m = getattr(self, 'build_' + o.__class__.__name__, None)
```

Note: It seems that nor `Builder.build` neither `Build.build_Getattr` are being used anymore. At least not in `configobj.py`. Git blame shows that they exist since the initial commit. I guess that no-one is using them.

**Comment by lambdafu** [comment]
This also prevents cython from working.
