### ISSUE TITLE
Please include readme/license and possibly other files in sdist

### ISSUE THREAD

**Issue by bkabrda** [DiffSK/configobj#63]
Hi,
would it be possible to include at least license and readme in sdist? It's really beneficial for downstream redistributors (e.g. Fedora, where I'm trying to update to latest configobj right now) to have at least these two. Adding the whole docs directory and tests would be also great - most packages do it AFAIK - but I guess it's not that necessary.
Thanks for considering.

**Comment by jhermann** [comment]
Can be closed (see #86).
