### ISSUE TITLE
Move _version.py into your namespace

### ISSUE THREAD

**Issue by bdrung** [DiffSK/configobj#72]
Currently `_version.py` is installed into `/usr/lib/python2.7/dist-packages/_version.py` or `/usr/lib/python3/dist-packages/_version.py`. There is no indication that `_version.py` belongs to configobj and could conflict with other project that do the same. So please rename _version.py to `configobj_version.py`, move it into a subdirectory, or completely get rid of it.

**Comment by jhermann** [comment]
Can be closed (see #86).
