### ISSUE TITLE
PyPI tarball is missing tests directory and doesn't match github release tarball

### ISSUE THREAD

**Issue by warsaw** [DiffSK/configobj#90]
The github v5.0.6 tar.gz release tarball contains the tests directory, but the version of the release on PyPI does not.  These two tarballs do not match.  They should be sha checksum identical, otherwise it will be unclear which is the definitive release.

**Comment by EliAndrewC** [comment]
That's an interesting point - are Python project "releases" on Github typically identical to what's on PyPI?

My understanding of a "Github release" is that it's basically just a tar.gz containing the current state of the Github repo as of the time we tagged a release.  It includes things like our ``.gitignore`` and ``.travis.yaml`` and such.  That's different than what a ``python setup.py sdist`` will generate, which is what ends up on PyPI and which shouldn't really include those things.

I'd therefore assumed until now that a "Github release" and a "PyPI release" were fundamentally different things and that it's okay for them to have different contents so long as the actual Python source files which they include are identical.  I'm happy to be corrected if that's not the accepted standard though.

**Comment by jhermann** [comment]
@EliAndrewC the situation should be better now, I think I updated the MANIFEST when moving the source into a package. 

Anyway, a good MANIFEST does indeed pack up anything of what's in git, but an sdist will always contain a few more files that the github snapshot, and be different.

**Comment by EliAndrewC** [comment]
Good to know, thanks for clarifying that.  Since the release files having different hashes is indeed expected, I'll go ahead and close this, since it sounds like there's no need to change anything.

**Comment by warsaw** [comment]
Thanks!  Having a complete tarball on PyPI (i.e. with tests directory) will work for us (Debian) even if it isn't a complete snapshot of the git repo (i.e. has no .travis-ci.yml).

**Comment by EliAndrewC** [comment]
Good to know.  I'll be cutting a new release next week with the improved manifest and everything else, so from that point forward all of the Github releases should have what you need.
