### ISSUE TITLE
_version in global namespace

### ISSUE THREAD

**Issue by cpaulik** [DiffSK/configobj#91]
Hi,

I noticed that installing configobj puts the file `_version.py` directly into `site-packages`.
This can cause conflicts if a package has their own `_version.py` file in the `PYTHONPATH`.

**Comment by jhermann** [comment]
Dupe of fixed #72.

**Comment by cpaulik** [comment]
Thanks. Sorry I forgot to search closed issues.

**Comment by EliAndrewC** [comment]
No problem, we always appreciate anyone who takes the time to file a bug report.  I'm planning on cutting the new release this week, so after that's out you shouldn't see this problem any longer.
