### ISSUE TITLE
Validator.check('string(min=1)', v) should fail if v is None

### ISSUE THREAD

**Issue by raff** [DiffSK/configobj#93]
Validating a string should fail if the value is None (at least in the cases where min >= 1). Currently it doesn't fail, but returns None (and I don't think this is documented anywhere)

**Comment by jhermann** [comment]
There is explicit code that always returns `None` unharmed, *unless* you add `missing=True`. See the tests in the linked commit. On the higher level `validate()` API everything works as expected anyway.
