### ISSUE TITLE
The release tarball does not contain instructions for testing

### ISSUE THREAD

**Issue by lfam** [DiffSK/configobj#96]
Can you provide some documentation on the testing procedures?

**Comment by EliAndrewC** [comment]
To clarify, are you asking for instructions on how to run the unit tests from a checkout of the project?

**Comment by lfam** [comment]
To be clear, I'm asking for instructions on running the tests from a release tarball, specifically the most recent one.

**Comment by jhermann** [comment]
@lfam please test this with the current HEAD, since the manifest now includes all project files, this should be no issue anymore.

Namely, the answer is "tox -e py27".
